name : Test

on: 
  schedule:
  # run every 5 minutes
    - cron: "*/5 * * * *"

  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout repo content
      uses: actions/checkout@v2
    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9.1 #install the python needed
    - name: Install requirements
      run: |
        pip install -r requirements.txt
    - name: Run File
      run: |
        python stock-market/test.py
      env:
        FROM_NUMBER : ${{ secrets.T_TWILIO_NUMBER }}
        ACCOUNT_SID : ${{ secrets.T_ACCOUNT_SID }}
        AUTH_TOKEN  : ${{ secrets.T_AUTH_TOKEN }}