name : Test

on: 
  schedule:
  # run every 5 minutes
  cron: "*/5 * * * *"
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: setup python
            with:
              python-version: 3.8 
          - name: execute py script 
            run: |
              python stock-market/test.py
